### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'stereo.libs.AANet.deform_conv'

### ISSUE THREAD

**Issue by lvruizhen** [XiandaGuo/OpenStereo#111]
when i run the train.py,this problem show:
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'stereo.libs.AANet.deform_conv' (most likely due to a circular import) (/home/lvrz/pythonproject/OpenStereo-2/./stereo/libs/AANet/deform_conv/__init__.py)
How to slove it,please!

**Comment by zhcm** [comment]
Please comment out aanet in stereo/modeling/__init__.py, or execute stereo/libs/AANet/deform_conv/build.sh to compile the deform_conv operator.
