### ISSUE TITLE
Why is the learning rate scheduler in the config file of the model zoo MultiStepLR?

### ISSUE THREAD

**Issue by yellowYuga** [XiandaGuo/OpenStereo#113]
Why is the learning rate scheduler in the config file in the model zoo MultiStepLR instead of OneCycleLR as stated in the paper?
![image](https://github.com/XiandaGuo/OpenStereo/assets/32639257/e46e04f9-2d0b-411a-98d9-694fdf872f47)

**Comment by XiandaGuo** [comment]
This table corresponds to the ablation experiments on StereoBase, which has not yet been open-sourced. The configurations in the model zoo are consistent with those in the original paper's settings.
