### ISSUE TITLE
Why the performances of cross-domain evaluation are not same as original paper?

### ISSUE THREAD

**Issue by lqxisok** [XiandaGuo/OpenStereo#115]
I'm trying to study the generalization problem of stereo matching models. But I find the performances of cross-domain evaluation in OpenStereo are worse than the results reported in other papers. E.g. from SF to Middlebury_H, IGEV achieves `7.1` 2-pixel error rate, `Validation MiddleburyH: EPE 0.9071302195390065, D1 7.276100820551316`. 
However, I got `{'d1_all': tensor(9.5060), 'epe': tensor(1.9520), 'thres_1': tensor(20.2628), 'thres_2': tensor(13.2752), 'thres_3': tensor(10.4775)}` when using the pretrained weight provided by OpenStereo. Could you plz explain why the performance are different?

**Comment by zhcm** [comment]
> I'm trying to study the generalization problem of stereo matching models. But I find the performances of cross-domain evaluation in OpenStereo are worse than the results reported in other papers. E.g. from SF to Middlebury_H, IGEV achieves `7.1` 2-pixel error rate, `Validation MiddleburyH: EPE 0.9071302195390065, D1 7.276100820551316`. However, I got `{'d1_all': tensor(9.5060), 'epe': tensor(1.9520), 'thres_1': tensor(20.2628), 'thres_2': tensor(13.2752), 'thres_3': tensor(10.4775)}` when using the pretrained weight provided by OpenStereo. Could you plz explain why the performance are different?

We have updated the code and model weights. Please re-download the model weights and pull the latest code.
