### ISSUE TITLE
无法推理

### ISSUE THREAD

**Issue by Hlll-huang** [XiandaGuo/OpenStereo#118]
你好，我想请问，推理lightstereo时候，模型的权重应该设置在哪里？为什么直接使用lightstereo还需要下载moblenet的权重？？？

**Comment by CaptainRui1000** [comment]
> 你好，我想请问，推理lightstereo时候，模型的权重应该设置在哪里？为什么直接使用lightstereo还需要下载moblenet的权重？？？

OpenStereo/stereo/modeling/models/lightstereo/backbone.py Backbone里面的pretrained改成=False就不需要下载moblenet了

lightstereo的权重可以在model zoo找到，https://drive.google.com/drive/folders/1eGtN_JAKy684ZP8gLTUemSgQxZir8hLf

**Comment by Hlll-huang** [comment]
已解决，感谢，但又存在新的问题，尝试使用官方权重推理kitti的第一张数据集，但得到的效果很差，想问问是什么原因，有解决方案吗？
![000000_10](https://github.com/user-attachments/assets/40ed44a8-cd14-4cef-855f-a16cee92a97e)

**Comment by Hlll-huang** [comment]
![Uploading 微信截图_20240723105113.png…]()

**Comment by Hlll-huang** [comment]
伪彩色图，如下所示
![0](https://github.com/user-attachments/assets/a98a89bb-fcf9-4a6c-9be6-b7cf1a3319ef)

**Comment by CaptainRui1000** [comment]
> 已解决，感谢，但又存在新的问题，尝试使用官方权重推理kitti的第一张数据集，但得到的效果很差，想问问是什么原因，有解决方案吗？ ![000000_10](https://private-user-images.githubusercontent.com/74290305/351168923-40ed44a8-cd14-4cef-855f-a16cee92a97e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQ0MTEsIm5iZiI6MTcyMTczNDExMSwicGF0aCI6Ii83NDI5MDMwNS8zNTExNjg5MjMtNDBlZDQ0YTgtY2QxNC00Y2VmLTg1NWYtYTE2Y2VlOTJhOTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZGRiN2I2OWY2NTMxNzljMmQzM2Y2NGRiMmUwNjQ5ZGViMzE1YTc0ZjgxMmM5ZTVhNDJlMmFhODBlYzYzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cKWqgrEj4K6xUCG-148ONHjdQVfHbJRHVXrMoUXeb2w)

请问推理的流程是怎么样的？

**Comment by Hlll-huang** [comment]
> > 已解决，感谢，但又存在新的问题，尝试使用官方权重推理kitti的第一张数据集，但得到的效果很差，想问问是什么原因，有解决方案吗？ ![000000_10](https://private-user-images.githubusercontent.com/74290305/351168923-40ed44a8-cd14-4cef-855f-a16cee92a97e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQ0MTEsIm5iZiI6MTcyMTczNDExMSwicGF0aCI6Ii83NDI5MDMwNS8zNTExNjg5MjMtNDBlZDQ0YTgtY2QxNC00Y2VmLTg1NWYtYTE2Y2VlOTJhOTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZGRiN2I2OWY2NTMxNzljMmQzM2Y2NGRiMmUwNjQ5ZGViMzE1YTc0ZjgxMmM5ZTVhNDJlMmFhODBlYzYzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cKWqgrEj4K6xUCG-148ONHjdQVfHbJRHVXrMoUXeb2w)
> 
> 请问是怎样的推理流程？
我在cfg的lightstereo_s_kitti.yaml文件里面的参数PRETRAINED_MODEL添加了官网的训练权重，然后运行python tools/infer.py 添加cfg_file和左右图路径。
![1](https://github.com/user-attachments/assets/eaa5e81d-f4c4-4d4e-afda-439383d50271)

**Comment by rachitagarwal2603** [comment]
In the tools/infer.py, on giving left and right image as input of dimension HxW. I see model predicts Hx(Wx3) dimension output. 
Here, as per my understanding, first channel represents disparity map. What does the other 2 channels represent?
