### ISSUE TITLE
Quick question on inference speed of LightStereo

### ISSUE THREAD

**Issue by Jm7752** [XiandaGuo/OpenStereo#120]
I have a few quick questions on the recently released LightStereo-S Model being released.  Currently I tried to use the infer python script and timed the evaluation time between the model inference and got something like 0.5Seconds.

 I understand that we have different GPU, you are using a Nvidia RTX 3090 and I am using a RTX 3070, but this timing seems almost some as 2d- MobileStereoNet which is also like 0.5seconds on my computer. 

This seems different from the paper where lightstereo should be an order of magnitude faster, so I am wondering if there is some additional optimization for lightstereo for speed than the infer.py script, or if you think it is just a hardware thing. 

https://github.com/XiandaGuo/OpenStereo/blob/v2/tools/infer.py

Additionally, It doesn't seem to function very well on grayscale images. Do you guys have a trick for improving the performance on that or is that outside of the Scope for Lightstereo.

KITTI grayscale image Stereo Matching

![infra1](https://github.com/user-attachments/assets/f3c1d390-3f6c-4215-9588-7c81a9b94596)
Infered Disparity
![img1](https://github.com/user-attachments/assets/fc62304d-174b-4db3-bcac-8e750989c48e)

Other examples out of distribution
![infra1](https://github.com/user-attachments/assets/23647bbb-9e8a-4aa4-adc8-a52b2811c0be)
Infred Disparity 
![img1(2)](https://github.com/user-attachments/assets/43b2454c-b155-47f8-8edb-264ced23452e)

Thanks

**Comment by zhcm** [comment]
@Jm7752 
please check tools/measure.py. 
The model's parameter count, computational cost, and inference speed will be analyzed.
Ensure there are no other tasks running on your GPU before starting.

**Comment by Jm7752** [comment]
Ok thanks will do
