### ISSUE TITLE
Infer error

### ISSUE THREAD

**Issue by paleriderrrr** [XiandaGuo/OpenStereo#124]
![图片](https://github.com/user-attachments/assets/bcad115e-ed37-4c9c-adfc-180f3318f97e)
感谢您的工作，请问在推理过程中出现not updated weight输出原因是什么？

**Comment by Hlll-huang** [comment]
我也遇到相同的问题，你解决了吗？

**Comment by zhcm** [comment]
Can you describe the question more clearly? Take a screenshot of the stack trace would be very useful. @paleriderrrr

**Comment by ZhihuLi** [comment]
我也遇到了这个问题，怎么解决啊

**Comment by Hlll-huang** [comment]
可能和timm版本相关，建议按照作者提供的库的版本安装
&nbsp;


黄路
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月6日(星期五) 晚上9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XiandaGuo/OpenStereo] Infer error (Issue #124)














 
我也遇到了这个问题，怎么解决啊

**Comment by ZhihuLi** [comment]
按照作者提供的库的版本安装了，还是有这个问题呢

**Comment by zhcm** [comment]
> 按照作者提供的库的版本安装了，还是有这个问题呢

What exactly is your problem? Can you provide the error message?

**Comment by zhcm** [comment]
Where is the "ERROR", can you point it? @ZhihuLi @Hlll-huang @paleriderrrr

**Comment by zhcm** [comment]
Where is the "ERROR", can you point it? i can only see "INFO" in the pic @ZhihuLi @Hlll-huang @paleriderrrr

**Comment by ZhihuLi** [comment]
In the last two rows of the picture, it says "Unused weight" "Not updated weight" , and the program exits at this point. Is this normal?



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/06/2024 23:42 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [XiandaGuo/OpenStereo] Infer error (Issue #124) |

Where is the "ERROR", can you point it? i can only see "INFO" in the pic @***@***.***@paleriderrrr

**Comment by zhcm** [comment]
It clearly says INFO in big letters, can you take a screenshot of the stack trace when your process crash? @ZhihuLi

**Comment by ZhihuLi** [comment]
This is a hint, not a mistake, I made a misunderstanding, thank you for your answer
