### ISSUE TITLE
Hello author, thank you for your work！ I have a problem.

### ISSUE THREAD

**Issue by asd9697** [XiandaGuo/OpenStereo#125]
I saw that your paper mentioned using repvit as a transformer type feature extraction. May I ask how to add repvit? Can you give me some help or release relevant code? Thank you very much!

**Comment by XiandaGuo** [comment]
Thanks for your interest in our work. You can communicate with me by email(xianda_guo@163.com)

**Comment by asd9697** [comment]
> Thanks for your interest in our work. You can communicate with me by email([xianda_guo@163.com](mailto:xianda_guo@163.com))

感谢全部，我联系您了

**Comment by asd9697** [comment]
> Thanks for your interest in our work. You can communicate with me by email([xianda_guo@163.com](mailto:xianda_guo@163.com))

感谢前辈，我联系您了
