### ISSUE TITLE
igev 相较于原官方的实现推理一对图像，耗时是官方的10倍左右？

### ISSUE THREAD

**Issue by nmber5** [XiandaGuo/OpenStereo#126]

**Comment by XiandaGuo** [comment]
Could you provide more specific details?

**Comment by nmber5** [comment]
看起来是输出disp图像分辨率大小的问题，怎么修改能让disp的分辨率与输入图像大小一样？

**Comment by nmber5** [comment]
640*480同样的分辨率，是比官方的igev推理慢，都是迭代32次，有啥不一样嘛
