### ISSUE TITLE
Training model using a model ckpt

### ISSUE THREAD

**Issue by danielvais** [XiandaGuo/OpenStereo#129]
Hi,
First of all thank you for this repo:)
I want to replicate some of the published results. How can I load a trained model to further train it?
This is needed to replicate the resluts on the KITTI2015 dataset where the paper says that the model was first trained on SceneFlow dataset and than further trained on KITTI2015.

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. You can place the model trained with Sceneflow in the path shown as follows:
<img width="889" alt="image" src="https://github.com/user-attachments/assets/be8bcf15-e9d0-44d2-8c55-9b212964b23f">
