### ISSUE TITLE
你好，关于步态识别grew Competition的问题

### ISSUE THREAD

**Issue by ZunxiaoXu** [XiandaGuo/OpenStereo#135]
![image](https://github.com/user-attachments/assets/376d59e3-dc8e-4bf8-92df-86361987f45c)
在图中界面，我上传了很多次zip results，全部没有响应。界面下放表格中也没有任何提交记录，请问如何解决？

**Comment by XiandaGuo** [comment]
It seems like it is caused by the deprecation of mutation events in Chrome. you can try to re-enable the deprecated mutation events in Chrome or edge. If you have any other questions, please leave a message at https://github.com/XiandaGuo/GREW-Benchmark.
