### ISSUE TITLE
Infering on different data

### ISSUE THREAD

**Issue by danielvais** [XiandaGuo/OpenStereo#139]
Hi,
I'm trying to use the code to get a disparity map on my own images (they are stereo).
I've successfully run the infer.py module on KITTI stereo images, but when I use my own images I encounter an error:
RuntimeError: The size of tensor a (60) must match the size of tensor b (59) at non-singleton dimension 3
(this happens in the psmnet_cost_proccessor.py module)
Any ideas my this doesnt work on any stereo images?

**Comment by XiandaGuo** [comment]
Which model are you using for inference? Some models require the input size to be a multiple of 16.
