### ISSUE TITLE
如何使用两个数据集训练

### ISSUE THREAD

**Issue by 13185742215** [XiandaGuo/OpenStereo#142]
1，如何实现在两个数据集上混合训练，或者串连地训练，能否给出yaml文件。
2，最大视差都设成了192，是否有道理，在训练时修改yaml文件中的最大视差值，能否影响训练结果。

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. The configuration files for mixed training on two or more datasets will be updated soon. Setting the maximum disparity to 192 is the default practice in most papers.
