### ISSUE TITLE
Inference on LightStereo fails

### ISSUE THREAD

**Issue by naik24** [XiandaGuo/OpenStereo#167]
Running inference right out of the box on LightStereo fails.

python3 tools/infer.py --cfg_file cfgs/lightstereo/lightstereo_s_sceneflow.yaml --left_img_path "input_images/im0.png" --right_img_path "input_images/im1.png"

<img width="1670" alt="image" src="https://github.com/user-attachments/assets/f3c99545-700a-4c50-9d4b-706e9680a422">

**Comment by CaptainRui1000** [comment]
what are the dimensions of the input left and right images you provided?  do they match the parameters in the yaml file?

**Comment by naik24** [comment]
The dimension of the input left and right image is 2964 x 1988

**Comment by naik24** [comment]
Solved! Looks like the issue is that the input dimensions (height, width) should be divisible by 32. Since my input dimensions were not divisible by 32, the inference was failing.

After resizing the input to dimensions divisible by 32, inference is successful!
