### ISSUE TITLE
StereoAnything Error: "nmrf_swint_sceneflow.py" not found

### ISSUE THREAD

**Issue by Jackson-agent** [XiandaGuo/OpenStereo#173]
Thank you for your work! I'm encountering an error while running the stereoanything inference  command in the project. It seems the script "nmrf_swint_sceneflow.py" is not included in the project. Additionally, when I try using the file "nmrf_swint_sceneflow.yaml" instead, the command still throws an error. Can you help solve it?

**Comment by XiandaGuo** [comment]
Sorry for this mistake. Could you send a screenshot of the error message you encountered when using "nmrf_swint_sceneflow.yaml"?

**Comment by Jackson-agent** [comment]
I've solved the previous issue I was facing regarding the args of the command.
I now have a new question. I want to assess the quality of disparity maps. I'd like to know if it's possible to:
- Convert disparity maps to depth maps.
- Convert disparity maps to point clouds, given intrinsic and extrinsic parameters.
