### ISSUE TITLE
StereoAnything to onnx

### ISSUE THREAD

**Issue by wushilian** [XiandaGuo/OpenStereo#176]
Stereoanything cannot be converted to onnx, can you solve it

**Comment by zhaoxin111** [comment]
hi, does the Stereoanything  code and ckpt released? I only see the paper :(

**Comment by wushilian** [comment]
> hi, does the Stereoanything code and ckpt released? I only see the paper :(

yes，look readme

**Comment by XiandaGuo** [comment]
The ckpt has been released at OpenStereo/docs/StereoAnything.md
