### ISSUE TITLE
A possible mistake in the LightStereo paper.

### ISSUE THREAD

**Issue by TheCuriousJoe** [XiandaGuo/OpenStereo#185]
In your paper "LightStereo: Channel Boost Is All Your Need for Efficient 2D Cost Aggregation", the computation time for HITNet is stated as 54ms, but in the original HITNet paper, the computation time is 20ms. 

Why is there this discrepancy?

![image](https://github.com/user-attachments/assets/8c92ca5c-a69f-40da-952e-e786f58b1b7f)
![image](https://github.com/user-attachments/assets/77cef79a-7f37-4615-adde-ea6fd2378238)

**Comment by XiandaGuo** [comment]
We referred to the paper "Accurate and Efficient Stereo Matching via Attention Concatenation Volume" for this result.
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/06b6b0f0-210d-4715-b3b5-ef064a70a16e" />

**Comment by TheCuriousJoe** [comment]
Could you please help me understand why the data from the original paper wasn't used, and what was the rationale behind using the data from this article instead?
