### ISSUE TITLE
Evaluation on ETH3D, MB and KITTI

### ISSUE THREAD

**Issue by TomTomTommi** [XiandaGuo/OpenStereo#47]
Hi, nice work!

I failed to find config files on ETH3D, MB, and KITTI. Could you please provide some commands on how to test on these datasets with the models trained on SceneFlow (if change data_cfg.name=ETH3D, then it cannot reload the checkpoint from SceneFlow)?

**Comment by ralph0813** [comment]
Hi, we have added config for [ETH3D and Middlebury](https://github.com/XiandaGuo/OpenStereo/pull/48#issue-2035752093) Dataset. For KITTI, please refer to [IGEV](https://github.com/XiandaGuo/OpenStereo/blob/main/configs/igev/igev_kitti.yaml).

To evaluate on these datasets, you can try following commonds:
`python openstereo/main.py --config configs/psmnet/PSMNet_MB.yaml --scope val --no_distribute --restore_hint path/to/weights`

Make sure you have downloaded the datasets and placed them just as the listfile shows in the yaml config.

**Comment by Guzaiwang** [comment]
When changing the evaluation file from MiddEval3_train_h.txt to MiddEval3_train_f.txt, this error will occur,

> RuntimeError: The size of tensor a (360) must match the size of tensor b (359) at non-singleton dimension 4

Could you help to fix it ?

**Comment by ralph0813** [comment]
@Guzaiwang Which model are you using? Generally speaking, this problem is caused by the incorrect size of the model input image. Try changing the input size to a multiple of 8, 12, or 16 to solve the problem.

**Comment by Guzaiwang** [comment]
> @Guzaiwang Which model are you using? Generally speaking, this problem is caused by the incorrect size of the model input image. Try changing the input size to a multiple of 8, 12, or 16 to solve the problem.

Using PSMNet_MB config. Thanks. I got it. 
By the way, have you evaluated PSM-Net on the full-size Middlebury dataset?  I find that out-of-memory errors will occur in the V100 GPU.

**Comment by ralph0813** [comment]
Yes, most models will encounter out-of-memory error when running full-szie evaluation, so the results in our paper use half-size.
