### ISSUE TITLE
Some model checkpoints are failed to be downloaded

### ISSUE THREAD

**Issue by lykasbongbongbong** [XiandaGuo/OpenStereo#51]
Hi! Thank you for the amazing work!

I've noticed that certain checkpoints on Baidu Pan, such as FADNet_sceneflow.pt and RAFT, failed to download properly. 
The problem seems to be that after downloading and extracting the checkpoints, the folder appears to be empty. 
Would you mind confirming this issue? Thanks!

**Comment by XiandaGuo** [comment]
Thank you so much for your kind words and support!  
To help us resolve this issue more effectively, could you please provide any specific error messages or logs you encountered during the download and extraction process?

**Comment by lykasbongbongbong** [comment]
Hi, 
The following is how I tried to download the checkpoints:
1. download the FADNet_sceneflow.pt here in your given link in model zoo: https://pan.baidu.com/s/13_kQq-N4AzBMe14KHJpYlA
2. Different from AANet_sceneflow.pt which is able to be downloaded directly (successfully saved as AANet_sceneflow.pt), the FADNet_sceneflow.pt, when downloaded, would be a baidunet_disk_4.17.7.amd64.deb file, which seems to be a download manager.
3. By extracting the downloaded baidunet_disk, the folder is empty.

**Comment by XiandaGuo** [comment]
I have already tested it, and the file can be downloaded.

**Comment by lykasbongbongbong** [comment]
Ah! I see. :) 
Seems like the downloading process has to go through Baidunet.

**Comment by XiandaGuo** [comment]
We have uploaded the checkpoint to Google Drive, which can be found at https://github.com/XiandaGuo/OpenStereo/blob/main/docs/1.model_zoo.md.
