### ISSUE TITLE
请问你这个模型针对的IGEV还是所有的呢？所有的立体匹配模型裁剪成320*736效果都比256*512要好吗

### ISSUE THREAD

**Issue by 1434205229** [XiandaGuo/OpenStereo#57]
![image](https://github.com/XiandaGuo/OpenStereo/assets/115446508/0c7f2367-a735-4ed2-b296-d122c2ce9d5e)

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. The data augmentation experiments were conducted based on StereoBase.
