### ISSUE TITLE
感谢，请问你们文章中复现的网络是FADNet还是FADNet++呢？因为注意到FADNet++好像没有完全开源。

### ISSUE THREAD

**Issue by flyxuexi** [XiandaGuo/OpenStereo#59]

**Comment by ralph0813** [comment]
As mentioned in our acknowledgments, the model we have replicated is FADNet.

**Comment by Yi-Qi638** [comment]
Hi, thanks for your interest in our work!

Currently, we support FADNet++. The default settings for FADNet++ are as follows:
encoder_ratio: 16
decoder_ratio: 16

**Comment by flyxuexi** [comment]
谢谢。我再看看
