### ISSUE TITLE
How to configure the "StereoBase" baseline model net work in your paper?

### ISSUE THREAD

**Issue by CaptainEven** [XiandaGuo/OpenStereo#60]
I can not find any definition of the "StereoBase" network arch, could you give me some advice to try it out?

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. Since our paper has not yet been officially accepted, the code for Sterebase has not been released.

**Comment by CaptainEven** [comment]
> Thank you for your interest in our work. Since our paper has not yet been officially accepted, the code for Sterebase has not been released.

got it

**Comment by XiandaGuo** [comment]
The code of StereoBase is available.
