### ISSUE TITLE
There are some issues with the configuration and reproduction of Raft-stereo

### ISSUE THREAD

**Issue by qylen** [XiandaGuo/OpenStereo#76]
Nice work!
However, I found that there is an issue with the data preprocessing section in the configuration file of the raft-stereo, which cannot run smoothly. After aligning with the data preprocessing section of the original raft-stereo, it can run normally.
However, there is a significant difference between EPE and the original version, and the convergence is also slow.
Could you please review the configuration and training process of the following raft-stereo again?
![image](https://github.com/XiandaGuo/OpenStereo/assets/94056015/8ffa2235-93fa-4ec6-bda3-d84d454e66f3)
This configuration can run through the code. However, whether or not data regularization is turned off, the effect is not ideal.

**Comment by duanyiqun** [comment]
Thanks for your good suggestion! 
We will keep tracking the configs and update the config if any progress comes.
