### ISSUE TITLE
Which pretrained model exactly is stereo base?

### ISSUE THREAD

**Issue by Rong-Tao** [XiandaGuo/OpenStereo#81]
In you paper I see some thing like this: 
![image](https://github.com/XiandaGuo/OpenStereo/assets/51011533/25c6b0e1-5c93-41dd-a95d-ca489f1ff837)
but which one in the model zoo exactly is this one?

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. Since our paper has not yet been officially accepted, the code for Sterebase has not been released.
