### ISSUE TITLE
The training strategies

### ISSUE THREAD

**Issue by zhuxing0** [XiandaGuo/OpenStereo#83]
The paper mentions that “each model was trained 90 epochs using a batch size of 64”, is this the same in the final training of Stereobase？What are the training strategies on the sceneflow and KITTI datasets respectively?
<img width="395" alt="image" src="https://github.com/XiandaGuo/OpenStereo/assets/84132236/022c26cb-8aed-4524-8b8d-a1f45f0ec428">

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. Since our paper has not yet been officially accepted, the code and the training strategies for Sterebase have not been released.
