### ISSUE TITLE
Is this article a review and finishing work of stereo matching？

### ISSUE THREAD

**Issue by progressforever** [XiandaGuo/OpenStereo#87]
Hi, this work is amazing! Thank you for your work. I want to ask two questions.
1.Is this article a review and finishing work of stereo matching? I don’t seem to see a network model named openstereo.
2.the data augumentation method ablation experiment seems not obviously. I can not select best combination of data augumentation method.
Wish your early reply.

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. "OpenStereo" is the name of the entire project.
