### ISSUE TITLE
Plan about model deployment

### ISSUE THREAD

**Issue by Daa98** [XiandaGuo/OpenStereo#92]
Is there any plan to add related implementation of model deployment?

**Comment by markchangsy** [comment]
@XiandaGuo

**Comment by zhcm** [comment]
> Is there any plan to add related implementation of model deployment?

Yes, we are working on tensorRT and will release soon

**Comment by XiandaGuo** [comment]
TensorRT has been integrated, please see the [Deployment documentation](https://github.com/XiandaGuo/OpenStereo/blob/v2/deploy/README.md)
