### ISSUE TITLE
Mistake in paper table7

### ISSUE THREAD

**Issue by Guptajakala** [XiandaGuo/OpenStereo#95]
![image](https://github.com/XiandaGuo/OpenStereo/assets/40518028/a0ea1f90-4573-4004-8f38-b339fd7ebdfc)
The results in the table do not seem to be on the same test set.

In STTR, it's evaluated on the flyingthings subset of sceneflow.
In IGEV, it's evaluated on the whole sceneflow

BTW, what is the set used in StereoBase?

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. The evaluation of the STTR model is limited to the FlyingThings subset, while the evaluation of all other models encompasses the whole SceneFlow test dataset.
