### ISSUE TITLE
Middlebury dataset download issue

### ISSUE THREAD

**Issue by zhangzscn** [XiandaGuo/OpenStereo#96]
Middlebury reference data sets the configuration of the tutorial to download the data sets, but the links in the tutorial (http://vision.middlebury.edu/stereo/data) in the corresponding page has multiple data sets: 2001, 2003, 2005, 2006, 2014, 2021. I downloaded them all, but when I unzipped them, there were no TrainingQ folders. So can you tell me the detailed download path?

**Comment by ralph0813** [comment]
Hi, you can use the [middlebury_tool.zip file](https://github.com/user-attachments/files/15625028/middlebury_tool.zip), which is obtained from the [MC-CNN](https://github.com/jzbontar/mc-cnn/blob/b944e2fb58b130a01ec70dd7314ed540e970f58a/download_middlebury.sh) project, to get the dataset.
