### ISSUE TITLE
Are the code and weights for StereoBase available?

### ISSUE THREAD

**Issue by MalekWahidi** [XiandaGuo/OpenStereo#97]
I have noticed the state-of-the-art StereoBase model is not available in this repo despite KITTI showing that the code for this model is publically available. Are there plans to release the model or is it private?

**Comment by XiandaGuo** [comment]
Thank you for your interest in our work. The code for Stereobase will be released once our paper has been officially accepted.

**Comment by XiandaGuo** [comment]
The code of StereoBase is available.
